
namespace Dissolution_of_a_solid_dosage_form
{
    partial class Dissolution_model
    {
        /// <summary>
        /// Обязательная переменная конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Освободить все используемые ресурсы.
        /// </summary>
        /// <param name="disposing">истинно, если управляемый ресурс должен быть удален; иначе ложно.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Код, автоматически созданный конструктором форм Windows

        /// <summary>
        /// Требуемый метод для поддержки конструктора — не изменяйте 
        /// содержимое этого метода с помощью редактора кода.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.splitter1 = new System.Windows.Forms.Splitter();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.nudConc = new System.Windows.Forms.NumericUpDown();
            this.butStart = new System.Windows.Forms.Button();
            this.butClose = new System.Windows.Forms.Button();
            this.pictProcess = new System.Windows.Forms.PictureBox();
            this.pictGraphic = new System.Windows.Forms.PictureBox();
            this.butStop = new System.Windows.Forms.Button();
            this.timerDisplay = new System.Windows.Forms.Timer(this.components);
            this.dom_Dt = new System.Windows.Forms.DomainUpDown();
            this.dom_k = new System.Windows.Forms.DomainUpDown();
            this.nudResol = new System.Windows.Forms.NumericUpDown();
            this.nudResolution = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.nudConc)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictProcess)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictGraphic)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudResol)).BeginInit();
            this.SuspendLayout();
            // 
            // splitter1
            // 
            this.splitter1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.splitter1.Location = new System.Drawing.Point(0, 0);
            this.splitter1.Name = "splitter1";
            this.splitter1.Size = new System.Drawing.Size(327, 710);
            this.splitter1.TabIndex = 0;
            this.splitter1.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Times New Roman", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label1.Location = new System.Drawing.Point(15, 26);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(292, 21);
            this.label1.TabIndex = 1;
            this.label1.Text = "Dissolution of a solid drug substance ";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Times New Roman", 10.2F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label2.Location = new System.Drawing.Point(13, 75);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(74, 19);
            this.label2.TabIndex = 2;
            this.label2.Text = "Exercise:";
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Times New Roman", 10.2F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label4.Location = new System.Drawing.Point(115, 118);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(167, 19);
            this.label4.TabIndex = 4;
            this.label4.Text = "Sat. sol. concentration";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Times New Roman", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(161, 201);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(155, 19);
            this.label5.TabIndex = 5;
            this.label5.Text = "Diffusion coefficient";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Times New Roman", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label6.Location = new System.Drawing.Point(161, 241);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(134, 19);
            this.label6.TabIndex = 6;
            this.label6.Text = "Dissolution factor";
            // 
            // nudConc
            // 
            this.nudConc.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.nudConc.Font = new System.Drawing.Font("Times New Roman", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.nudConc.Location = new System.Drawing.Point(44, 116);
            this.nudConc.Maximum = new decimal(new int[] {
            20,
            0,
            0,
            0});
            this.nudConc.Minimum = new decimal(new int[] {
            10,
            0,
            0,
            0});
            this.nudConc.Name = "nudConc";
            this.nudConc.Size = new System.Drawing.Size(54, 27);
            this.nudConc.TabIndex = 8;
            this.nudConc.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.nudConc.Value = new decimal(new int[] {
            10,
            0,
            0,
            0});
            // 
            // butStart
            // 
            this.butStart.AutoSize = true;
            this.butStart.BackColor = System.Drawing.Color.Pink;
            this.butStart.Cursor = System.Windows.Forms.Cursors.Hand;
            this.butStart.FlatAppearance.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.butStart.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.butStart.Location = new System.Drawing.Point(30, 375);
            this.butStart.Name = "butStart";
            this.butStart.Size = new System.Drawing.Size(277, 78);
            this.butStart.TabIndex = 11;
            this.butStart.Text = "START";
            this.butStart.UseVisualStyleBackColor = false;
            this.butStart.Click += new System.EventHandler(this.butStart_Click);
            this.butStart.MouseEnter += new System.EventHandler(this.butStart_MouseEnter);
            this.butStart.MouseLeave += new System.EventHandler(this.butStart_MouseLeave);
            // 
            // butClose
            // 
            this.butClose.AutoSize = true;
            this.butClose.BackColor = System.Drawing.Color.LawnGreen;
            this.butClose.Cursor = System.Windows.Forms.Cursors.Hand;
            this.butClose.Font = new System.Drawing.Font("Times New Roman", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.butClose.Location = new System.Drawing.Point(74, 656);
            this.butClose.Name = "butClose";
            this.butClose.Size = new System.Drawing.Size(188, 42);
            this.butClose.TabIndex = 12;
            this.butClose.Text = "CLOSE";
            this.butClose.UseVisualStyleBackColor = false;
            this.butClose.Click += new System.EventHandler(this.butClose_Click);
            this.butClose.MouseEnter += new System.EventHandler(this.butClose_MouseEnter);
            this.butClose.MouseLeave += new System.EventHandler(this.butClose_MouseLeave);
            // 
            // pictProcess
            // 
            this.pictProcess.Location = new System.Drawing.Point(365, 0);
            this.pictProcess.Name = "pictProcess";
            this.pictProcess.Size = new System.Drawing.Size(719, 394);
            this.pictProcess.TabIndex = 13;
            this.pictProcess.TabStop = false;
            // 
            // pictGraphic
            // 
            this.pictGraphic.Location = new System.Drawing.Point(365, 400);
            this.pictGraphic.Name = "pictGraphic";
            this.pictGraphic.Size = new System.Drawing.Size(719, 310);
            this.pictGraphic.TabIndex = 14;
            this.pictGraphic.TabStop = false;
            // 
            // butStop
            // 
            this.butStop.AutoSize = true;
            this.butStop.BackColor = System.Drawing.Color.LightBlue;
            this.butStop.Cursor = System.Windows.Forms.Cursors.Hand;
            this.butStop.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.butStop.Location = new System.Drawing.Point(30, 459);
            this.butStop.Name = "butStop";
            this.butStop.Size = new System.Drawing.Size(277, 78);
            this.butStop.TabIndex = 15;
            this.butStop.Text = "STOP";
            this.butStop.UseVisualStyleBackColor = false;
            this.butStop.Click += new System.EventHandler(this.butStop_Click);
            this.butStop.MouseEnter += new System.EventHandler(this.butStop_MouseEnter);
            this.butStop.MouseLeave += new System.EventHandler(this.butStop_MouseLeave);
            // 
            // timerDisplay
            // 
            this.timerDisplay.Interval = 50;
            this.timerDisplay.Tick += new System.EventHandler(this.timerDisplay_Tick);
            // 
            // dom_Dt
            // 
            this.dom_Dt.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.dom_Dt.Items.Add("0,1");
            this.dom_Dt.Items.Add("0,101");
            this.dom_Dt.Items.Add("0,102");
            this.dom_Dt.Items.Add("0,103");
            this.dom_Dt.Items.Add("0,104");
            this.dom_Dt.Items.Add("0,105");
            this.dom_Dt.Items.Add("0,106");
            this.dom_Dt.Items.Add("0,107");
            this.dom_Dt.Items.Add("0,108");
            this.dom_Dt.Items.Add("0,109");
            this.dom_Dt.Items.Add("0,11");
            this.dom_Dt.Items.Add("0,111");
            this.dom_Dt.Items.Add("0,112");
            this.dom_Dt.Items.Add("0,113");
            this.dom_Dt.Items.Add("0,114");
            this.dom_Dt.Items.Add("0,115");
            this.dom_Dt.Items.Add("0,116");
            this.dom_Dt.Items.Add("0,117");
            this.dom_Dt.Items.Add("0,118");
            this.dom_Dt.Items.Add("0,119");
            this.dom_Dt.Items.Add("0,12");
            this.dom_Dt.Items.Add("0,121");
            this.dom_Dt.Items.Add("0,122");
            this.dom_Dt.Items.Add("0,123");
            this.dom_Dt.Items.Add("0,124");
            this.dom_Dt.Items.Add("0,125");
            this.dom_Dt.Items.Add("0,126");
            this.dom_Dt.Items.Add("0,127");
            this.dom_Dt.Items.Add("0,128");
            this.dom_Dt.Items.Add("0,129");
            this.dom_Dt.Items.Add("0,13");
            this.dom_Dt.Items.Add("0,131");
            this.dom_Dt.Items.Add("0,132");
            this.dom_Dt.Items.Add("0,133");
            this.dom_Dt.Items.Add("0,134");
            this.dom_Dt.Items.Add("0,135");
            this.dom_Dt.Items.Add("0,136");
            this.dom_Dt.Items.Add("0,137");
            this.dom_Dt.Items.Add("0,138");
            this.dom_Dt.Items.Add("0,139");
            this.dom_Dt.Items.Add("0,14");
            this.dom_Dt.Items.Add("0,141");
            this.dom_Dt.Items.Add("0,142");
            this.dom_Dt.Items.Add("0,143");
            this.dom_Dt.Items.Add("0,144");
            this.dom_Dt.Items.Add("0,145");
            this.dom_Dt.Items.Add("0,146");
            this.dom_Dt.Items.Add("0,147");
            this.dom_Dt.Items.Add("0,148");
            this.dom_Dt.Items.Add("0,149");
            this.dom_Dt.Items.Add("0,15");
            this.dom_Dt.Items.Add("0,151");
            this.dom_Dt.Items.Add("0,152");
            this.dom_Dt.Items.Add("0,153");
            this.dom_Dt.Items.Add("0,154");
            this.dom_Dt.Items.Add("0,155");
            this.dom_Dt.Items.Add("0,156");
            this.dom_Dt.Items.Add("0,157");
            this.dom_Dt.Items.Add("0,158");
            this.dom_Dt.Items.Add("0,159");
            this.dom_Dt.Items.Add("0,16");
            this.dom_Dt.Items.Add("0,161");
            this.dom_Dt.Items.Add("0,162");
            this.dom_Dt.Items.Add("0,163");
            this.dom_Dt.Items.Add("0,164");
            this.dom_Dt.Items.Add("0,165");
            this.dom_Dt.Items.Add("0,166");
            this.dom_Dt.Items.Add("0,167");
            this.dom_Dt.Items.Add("0,168");
            this.dom_Dt.Items.Add("0,169");
            this.dom_Dt.Items.Add("0,17");
            this.dom_Dt.Items.Add("0,171");
            this.dom_Dt.Items.Add("0,172");
            this.dom_Dt.Items.Add("0,173");
            this.dom_Dt.Items.Add("0,174");
            this.dom_Dt.Items.Add("0,175");
            this.dom_Dt.Items.Add("0,176");
            this.dom_Dt.Items.Add("0,177");
            this.dom_Dt.Items.Add("0,178");
            this.dom_Dt.Items.Add("0,179");
            this.dom_Dt.Items.Add("0,18");
            this.dom_Dt.Items.Add("0,181");
            this.dom_Dt.Items.Add("0,182");
            this.dom_Dt.Items.Add("0,183");
            this.dom_Dt.Items.Add("0,184");
            this.dom_Dt.Items.Add("0,185");
            this.dom_Dt.Items.Add("0,186");
            this.dom_Dt.Items.Add("0,187");
            this.dom_Dt.Items.Add("0,188");
            this.dom_Dt.Items.Add("0,189");
            this.dom_Dt.Items.Add("0,19");
            this.dom_Dt.Items.Add("0,191");
            this.dom_Dt.Items.Add("0,192");
            this.dom_Dt.Items.Add("0,193");
            this.dom_Dt.Items.Add("0,194");
            this.dom_Dt.Items.Add("0,195");
            this.dom_Dt.Items.Add("0,196");
            this.dom_Dt.Items.Add("0,197");
            this.dom_Dt.Items.Add("0,198");
            this.dom_Dt.Items.Add("0,199");
            this.dom_Dt.Items.Add("0,2");
            this.dom_Dt.Location = new System.Drawing.Point(63, 195);
            this.dom_Dt.Name = "dom_Dt";
            this.dom_Dt.Size = new System.Drawing.Size(92, 25);
            this.dom_Dt.TabIndex = 16;
            this.dom_Dt.Text = "choice_Dt";
            // 
            // dom_k
            // 
            this.dom_k.Font = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.dom_k.Items.Add("0,0009");
            this.dom_k.Items.Add("0,001");
            this.dom_k.Items.Add("0,002");
            this.dom_k.Items.Add("0,003");
            this.dom_k.Items.Add("0,004");
            this.dom_k.Items.Add("0,005");
            this.dom_k.Items.Add("0,006");
            this.dom_k.Items.Add("0,007");
            this.dom_k.Items.Add("0,008");
            this.dom_k.Items.Add("0,009");
            this.dom_k.Items.Add("0,01");
            this.dom_k.Items.Add("0,011");
            this.dom_k.Items.Add("0,012");
            this.dom_k.Items.Add("0,013");
            this.dom_k.Items.Add("0,014");
            this.dom_k.Items.Add("0,015");
            this.dom_k.Items.Add("0,016");
            this.dom_k.Items.Add("0,017");
            this.dom_k.Items.Add("0,018");
            this.dom_k.Items.Add("0,019");
            this.dom_k.Items.Add("0,02");
            this.dom_k.Items.Add("0,021");
            this.dom_k.Items.Add("0,022");
            this.dom_k.Items.Add("0,023");
            this.dom_k.Items.Add("0,024");
            this.dom_k.Items.Add("0,025");
            this.dom_k.Items.Add("0,026");
            this.dom_k.Items.Add("0,027");
            this.dom_k.Items.Add("0,028");
            this.dom_k.Items.Add("0,029");
            this.dom_k.Items.Add("0,03");
            this.dom_k.Items.Add("0,031");
            this.dom_k.Items.Add("0,032");
            this.dom_k.Items.Add("0,033");
            this.dom_k.Items.Add("0,034");
            this.dom_k.Items.Add("0,035");
            this.dom_k.Items.Add("0,036");
            this.dom_k.Items.Add("0,037");
            this.dom_k.Items.Add("0,038");
            this.dom_k.Items.Add("0,039");
            this.dom_k.Items.Add("0,04");
            this.dom_k.Items.Add("0,041");
            this.dom_k.Items.Add("0,042");
            this.dom_k.Items.Add("0,043");
            this.dom_k.Items.Add("0,044");
            this.dom_k.Items.Add("0,045");
            this.dom_k.Items.Add("0,046");
            this.dom_k.Items.Add("0,047");
            this.dom_k.Items.Add("0,048");
            this.dom_k.Items.Add("0,049");
            this.dom_k.Items.Add("0,05");
            this.dom_k.Items.Add("0,051");
            this.dom_k.Items.Add("0,052");
            this.dom_k.Items.Add("0,053");
            this.dom_k.Items.Add("0,054");
            this.dom_k.Items.Add("0,055");
            this.dom_k.Items.Add("0,056");
            this.dom_k.Items.Add("0,057");
            this.dom_k.Items.Add("0,058");
            this.dom_k.Items.Add("0,059");
            this.dom_k.Items.Add("0,06");
            this.dom_k.Items.Add("0,061");
            this.dom_k.Items.Add("0,062");
            this.dom_k.Items.Add("0,063");
            this.dom_k.Items.Add("0,064");
            this.dom_k.Items.Add("0,065");
            this.dom_k.Items.Add("0,066");
            this.dom_k.Items.Add("0,067");
            this.dom_k.Items.Add("0,068");
            this.dom_k.Items.Add("0,069");
            this.dom_k.Items.Add("0,07");
            this.dom_k.Items.Add("0,071");
            this.dom_k.Items.Add("0,072");
            this.dom_k.Items.Add("0,073");
            this.dom_k.Items.Add("0,074");
            this.dom_k.Items.Add("0,075");
            this.dom_k.Items.Add("0,076");
            this.dom_k.Items.Add("0,077");
            this.dom_k.Items.Add("0,078");
            this.dom_k.Items.Add("0,079");
            this.dom_k.Items.Add("0,08");
            this.dom_k.Items.Add("0,081");
            this.dom_k.Items.Add("0,082");
            this.dom_k.Items.Add("0,083");
            this.dom_k.Items.Add("0,084");
            this.dom_k.Items.Add("0,085");
            this.dom_k.Items.Add("0,086");
            this.dom_k.Items.Add("0,087");
            this.dom_k.Items.Add("0,088");
            this.dom_k.Items.Add("0,089");
            this.dom_k.Items.Add("0,09");
            this.dom_k.Items.Add("0,091");
            this.dom_k.Items.Add("0,092");
            this.dom_k.Items.Add("0,093");
            this.dom_k.Items.Add("0,094");
            this.dom_k.Items.Add("0,095");
            this.dom_k.Items.Add("0,096");
            this.dom_k.Items.Add("0,097");
            this.dom_k.Items.Add("0,098");
            this.dom_k.Items.Add("0,099");
            this.dom_k.Items.Add("0,1");
            this.dom_k.Items.Add("0,101");
            this.dom_k.Items.Add("0,102");
            this.dom_k.Items.Add("0,103");
            this.dom_k.Items.Add("0,104");
            this.dom_k.Items.Add("0,105");
            this.dom_k.Items.Add("0,106");
            this.dom_k.Items.Add("0,107");
            this.dom_k.Items.Add("0,108");
            this.dom_k.Items.Add("0,109");
            this.dom_k.Items.Add("0,11");
            this.dom_k.Items.Add("0,111");
            this.dom_k.Items.Add("0,112");
            this.dom_k.Items.Add("0,113");
            this.dom_k.Items.Add("0,114");
            this.dom_k.Items.Add("0,115");
            this.dom_k.Items.Add("0,116");
            this.dom_k.Items.Add("0,117");
            this.dom_k.Items.Add("0,118");
            this.dom_k.Items.Add("0,119");
            this.dom_k.Items.Add("0,12");
            this.dom_k.Items.Add("0,121");
            this.dom_k.Items.Add("0,122");
            this.dom_k.Items.Add("0,123");
            this.dom_k.Items.Add("0,124");
            this.dom_k.Items.Add("0,125");
            this.dom_k.Items.Add("0,126");
            this.dom_k.Items.Add("0,127");
            this.dom_k.Items.Add("0,128");
            this.dom_k.Items.Add("0,129");
            this.dom_k.Items.Add("0,13");
            this.dom_k.Items.Add("0,131");
            this.dom_k.Items.Add("0,132");
            this.dom_k.Items.Add("0,133");
            this.dom_k.Items.Add("0,134");
            this.dom_k.Items.Add("0,135");
            this.dom_k.Items.Add("0,136");
            this.dom_k.Items.Add("0,137");
            this.dom_k.Items.Add("0,138");
            this.dom_k.Items.Add("0,139");
            this.dom_k.Items.Add("0,14");
            this.dom_k.Items.Add("0,141");
            this.dom_k.Items.Add("0,142");
            this.dom_k.Items.Add("0,143");
            this.dom_k.Items.Add("0,144");
            this.dom_k.Items.Add("0,145");
            this.dom_k.Items.Add("0,146");
            this.dom_k.Items.Add("0,147");
            this.dom_k.Items.Add("0,148");
            this.dom_k.Items.Add("0,149");
            this.dom_k.Items.Add("0,15");
            this.dom_k.Items.Add("0,151");
            this.dom_k.Items.Add("0,152");
            this.dom_k.Items.Add("0,153");
            this.dom_k.Items.Add("0,154");
            this.dom_k.Items.Add("0,155");
            this.dom_k.Items.Add("0,156");
            this.dom_k.Items.Add("0,157");
            this.dom_k.Items.Add("0,158");
            this.dom_k.Items.Add("0,159");
            this.dom_k.Items.Add("0,16");
            this.dom_k.Items.Add("0,161");
            this.dom_k.Items.Add("0,162");
            this.dom_k.Items.Add("0,163");
            this.dom_k.Items.Add("0,164");
            this.dom_k.Items.Add("0,165");
            this.dom_k.Items.Add("0,166");
            this.dom_k.Items.Add("0,167");
            this.dom_k.Items.Add("0,168");
            this.dom_k.Items.Add("0,169");
            this.dom_k.Items.Add("0,17");
            this.dom_k.Items.Add("0,171");
            this.dom_k.Items.Add("0,172");
            this.dom_k.Items.Add("0,173");
            this.dom_k.Items.Add("0,174");
            this.dom_k.Items.Add("0,175");
            this.dom_k.Items.Add("0,176");
            this.dom_k.Items.Add("0,177");
            this.dom_k.Items.Add("0,178");
            this.dom_k.Items.Add("0,179");
            this.dom_k.Items.Add("0,18");
            this.dom_k.Items.Add("0,181");
            this.dom_k.Items.Add("0,182");
            this.dom_k.Items.Add("0,183");
            this.dom_k.Items.Add("0,184");
            this.dom_k.Items.Add("0,185");
            this.dom_k.Items.Add("0,186");
            this.dom_k.Items.Add("0,187");
            this.dom_k.Items.Add("0,188");
            this.dom_k.Items.Add("0,189");
            this.dom_k.Items.Add("0,19");
            this.dom_k.Items.Add("0,191");
            this.dom_k.Items.Add("0,192");
            this.dom_k.Items.Add("0,193");
            this.dom_k.Items.Add("0,194");
            this.dom_k.Items.Add("0,195");
            this.dom_k.Items.Add("0,196");
            this.dom_k.Items.Add("0,197");
            this.dom_k.Items.Add("0,198");
            this.dom_k.Items.Add("0,199");
            this.dom_k.Items.Add("0,2");
            this.dom_k.Items.Add("0,201");
            this.dom_k.Items.Add("0,202");
            this.dom_k.Items.Add("0,203");
            this.dom_k.Items.Add("0,204");
            this.dom_k.Items.Add("0,205");
            this.dom_k.Items.Add("0,206");
            this.dom_k.Items.Add("0,207");
            this.dom_k.Items.Add("0,208");
            this.dom_k.Items.Add("0,209");
            this.dom_k.Items.Add("0,21");
            this.dom_k.Items.Add("0,211");
            this.dom_k.Items.Add("0,212");
            this.dom_k.Items.Add("0,213");
            this.dom_k.Items.Add("0,214");
            this.dom_k.Items.Add("0,215");
            this.dom_k.Items.Add("0,216");
            this.dom_k.Items.Add("0,217");
            this.dom_k.Items.Add("0,218");
            this.dom_k.Items.Add("0,219");
            this.dom_k.Items.Add("0,22");
            this.dom_k.Items.Add("0,221");
            this.dom_k.Items.Add("0,222");
            this.dom_k.Items.Add("0,223");
            this.dom_k.Items.Add("0,224");
            this.dom_k.Items.Add("0,225");
            this.dom_k.Items.Add("0,226");
            this.dom_k.Items.Add("0,227");
            this.dom_k.Items.Add("0,228");
            this.dom_k.Items.Add("0,229");
            this.dom_k.Items.Add("0,23");
            this.dom_k.Items.Add("0,231");
            this.dom_k.Items.Add("0,232");
            this.dom_k.Items.Add("0,233");
            this.dom_k.Items.Add("0,234");
            this.dom_k.Items.Add("0,235");
            this.dom_k.Items.Add("0,236");
            this.dom_k.Items.Add("0,237");
            this.dom_k.Items.Add("0,238");
            this.dom_k.Items.Add("0,239");
            this.dom_k.Items.Add("0,24");
            this.dom_k.Items.Add("0,241");
            this.dom_k.Items.Add("0,242");
            this.dom_k.Items.Add("0,243");
            this.dom_k.Items.Add("0,244");
            this.dom_k.Items.Add("0,245");
            this.dom_k.Items.Add("0,246");
            this.dom_k.Items.Add("0,247");
            this.dom_k.Items.Add("0,248");
            this.dom_k.Items.Add("0,249");
            this.dom_k.Items.Add("0,25");
            this.dom_k.Items.Add("0,251");
            this.dom_k.Items.Add("0,252");
            this.dom_k.Items.Add("0,253");
            this.dom_k.Items.Add("0,254");
            this.dom_k.Items.Add("0,255");
            this.dom_k.Items.Add("0,256");
            this.dom_k.Items.Add("0,257");
            this.dom_k.Items.Add("0,258");
            this.dom_k.Items.Add("0,259");
            this.dom_k.Items.Add("0,26");
            this.dom_k.Items.Add("0,261");
            this.dom_k.Items.Add("0,262");
            this.dom_k.Items.Add("0,263");
            this.dom_k.Items.Add("0,264");
            this.dom_k.Items.Add("0,265");
            this.dom_k.Items.Add("0,266");
            this.dom_k.Items.Add("0,267");
            this.dom_k.Items.Add("0,268");
            this.dom_k.Items.Add("0,269");
            this.dom_k.Items.Add("0,27");
            this.dom_k.Items.Add("0,271");
            this.dom_k.Items.Add("0,272");
            this.dom_k.Items.Add("0,273");
            this.dom_k.Items.Add("0,274");
            this.dom_k.Items.Add("0,275");
            this.dom_k.Items.Add("0,276");
            this.dom_k.Items.Add("0,277");
            this.dom_k.Items.Add("0,278");
            this.dom_k.Items.Add("0,279");
            this.dom_k.Items.Add("0,28");
            this.dom_k.Items.Add("0,281");
            this.dom_k.Items.Add("0,282");
            this.dom_k.Items.Add("0,283");
            this.dom_k.Items.Add("0,284");
            this.dom_k.Items.Add("0,285");
            this.dom_k.Items.Add("0,286");
            this.dom_k.Items.Add("0,287");
            this.dom_k.Items.Add("0,288");
            this.dom_k.Items.Add("0,289");
            this.dom_k.Items.Add("0,29");
            this.dom_k.Items.Add("0,291");
            this.dom_k.Items.Add("0,292");
            this.dom_k.Items.Add("0,293");
            this.dom_k.Items.Add("0,294");
            this.dom_k.Items.Add("0,295");
            this.dom_k.Items.Add("0,296");
            this.dom_k.Items.Add("0,297");
            this.dom_k.Items.Add("0,298");
            this.dom_k.Items.Add("0,299");
            this.dom_k.Items.Add("0,3");
            this.dom_k.Items.Add("0,301");
            this.dom_k.Items.Add("0,302");
            this.dom_k.Items.Add("0,303");
            this.dom_k.Items.Add("0,304");
            this.dom_k.Items.Add("0,305");
            this.dom_k.Items.Add("0,306");
            this.dom_k.Items.Add("0,307");
            this.dom_k.Items.Add("0,308");
            this.dom_k.Items.Add("0,309");
            this.dom_k.Items.Add("0,31");
            this.dom_k.Items.Add("0,311");
            this.dom_k.Items.Add("0,312");
            this.dom_k.Items.Add("0,313");
            this.dom_k.Items.Add("0,314");
            this.dom_k.Items.Add("0,315");
            this.dom_k.Items.Add("0,316");
            this.dom_k.Items.Add("0,317");
            this.dom_k.Items.Add("0,318");
            this.dom_k.Items.Add("0,319");
            this.dom_k.Items.Add("0,32");
            this.dom_k.Items.Add("0,321");
            this.dom_k.Items.Add("0,322");
            this.dom_k.Items.Add("0,323");
            this.dom_k.Items.Add("0,324");
            this.dom_k.Items.Add("0,325");
            this.dom_k.Items.Add("0,326");
            this.dom_k.Items.Add("0,327");
            this.dom_k.Items.Add("0,328");
            this.dom_k.Items.Add("0,329");
            this.dom_k.Items.Add("0,33");
            this.dom_k.Items.Add("0,331");
            this.dom_k.Items.Add("0,332");
            this.dom_k.Items.Add("0,333");
            this.dom_k.Items.Add("0,334");
            this.dom_k.Items.Add("0,335");
            this.dom_k.Items.Add("0,336");
            this.dom_k.Items.Add("0,337");
            this.dom_k.Items.Add("0,338");
            this.dom_k.Items.Add("0,339");
            this.dom_k.Items.Add("0,34");
            this.dom_k.Items.Add("0,341");
            this.dom_k.Items.Add("0,342");
            this.dom_k.Items.Add("0,343");
            this.dom_k.Items.Add("0,344");
            this.dom_k.Items.Add("0,345");
            this.dom_k.Items.Add("0,346");
            this.dom_k.Items.Add("0,347");
            this.dom_k.Items.Add("0,348");
            this.dom_k.Items.Add("0,349");
            this.dom_k.Items.Add("0,35");
            this.dom_k.Items.Add("0,351");
            this.dom_k.Items.Add("0,352");
            this.dom_k.Items.Add("0,353");
            this.dom_k.Items.Add("0,354");
            this.dom_k.Items.Add("0,355");
            this.dom_k.Items.Add("0,356");
            this.dom_k.Items.Add("0,357");
            this.dom_k.Items.Add("0,358");
            this.dom_k.Items.Add("0,359");
            this.dom_k.Items.Add("0,36");
            this.dom_k.Items.Add("0,361");
            this.dom_k.Items.Add("0,362");
            this.dom_k.Items.Add("0,363");
            this.dom_k.Items.Add("0,364");
            this.dom_k.Items.Add("0,365");
            this.dom_k.Items.Add("0,366");
            this.dom_k.Items.Add("0,367");
            this.dom_k.Items.Add("0,368");
            this.dom_k.Items.Add("0,369");
            this.dom_k.Items.Add("0,37");
            this.dom_k.Items.Add("0,371");
            this.dom_k.Items.Add("0,372");
            this.dom_k.Items.Add("0,373");
            this.dom_k.Items.Add("0,374");
            this.dom_k.Items.Add("0,375");
            this.dom_k.Items.Add("0,376");
            this.dom_k.Items.Add("0,377");
            this.dom_k.Items.Add("0,378");
            this.dom_k.Items.Add("0,379");
            this.dom_k.Items.Add("0,38");
            this.dom_k.Items.Add("0,381");
            this.dom_k.Items.Add("0,382");
            this.dom_k.Items.Add("0,383");
            this.dom_k.Items.Add("0,384");
            this.dom_k.Items.Add("0,385");
            this.dom_k.Items.Add("0,386");
            this.dom_k.Items.Add("0,387");
            this.dom_k.Items.Add("0,388");
            this.dom_k.Items.Add("0,389");
            this.dom_k.Items.Add("0,39");
            this.dom_k.Items.Add("0,391");
            this.dom_k.Items.Add("0,392");
            this.dom_k.Items.Add("0,393");
            this.dom_k.Items.Add("0,394");
            this.dom_k.Items.Add("0,395");
            this.dom_k.Items.Add("0,396");
            this.dom_k.Items.Add("0,397");
            this.dom_k.Items.Add("0,398");
            this.dom_k.Items.Add("0,399");
            this.dom_k.Items.Add("0,4");
            this.dom_k.Items.Add("0,401");
            this.dom_k.Items.Add("0,402");
            this.dom_k.Items.Add("0,403");
            this.dom_k.Items.Add("0,404");
            this.dom_k.Items.Add("0,405");
            this.dom_k.Items.Add("0,406");
            this.dom_k.Items.Add("0,407");
            this.dom_k.Items.Add("0,408");
            this.dom_k.Items.Add("0,409");
            this.dom_k.Items.Add("0,41");
            this.dom_k.Items.Add("0,411");
            this.dom_k.Items.Add("0,412");
            this.dom_k.Items.Add("0,413");
            this.dom_k.Items.Add("0,414");
            this.dom_k.Items.Add("0,415");
            this.dom_k.Items.Add("0,416");
            this.dom_k.Items.Add("0,417");
            this.dom_k.Items.Add("0,418");
            this.dom_k.Items.Add("0,419");
            this.dom_k.Items.Add("0,42");
            this.dom_k.Items.Add("0,421");
            this.dom_k.Items.Add("0,422");
            this.dom_k.Items.Add("0,423");
            this.dom_k.Items.Add("0,424");
            this.dom_k.Items.Add("0,425");
            this.dom_k.Items.Add("0,426");
            this.dom_k.Items.Add("0,427");
            this.dom_k.Items.Add("0,428");
            this.dom_k.Items.Add("0,429");
            this.dom_k.Items.Add("0,43");
            this.dom_k.Items.Add("0,431");
            this.dom_k.Items.Add("0,432");
            this.dom_k.Items.Add("0,433");
            this.dom_k.Items.Add("0,434");
            this.dom_k.Items.Add("0,435");
            this.dom_k.Items.Add("0,436");
            this.dom_k.Items.Add("0,437");
            this.dom_k.Items.Add("0,438");
            this.dom_k.Items.Add("0,439");
            this.dom_k.Items.Add("0,44");
            this.dom_k.Items.Add("0,441");
            this.dom_k.Items.Add("0,442");
            this.dom_k.Items.Add("0,443");
            this.dom_k.Items.Add("0,444");
            this.dom_k.Items.Add("0,445");
            this.dom_k.Items.Add("0,446");
            this.dom_k.Items.Add("0,447");
            this.dom_k.Items.Add("0,448");
            this.dom_k.Items.Add("0,449");
            this.dom_k.Items.Add("0,45");
            this.dom_k.Items.Add("0,451");
            this.dom_k.Items.Add("0,452");
            this.dom_k.Items.Add("0,453");
            this.dom_k.Items.Add("0,454");
            this.dom_k.Items.Add("0,455");
            this.dom_k.Items.Add("0,456");
            this.dom_k.Items.Add("0,457");
            this.dom_k.Items.Add("0,458");
            this.dom_k.Items.Add("0,459");
            this.dom_k.Items.Add("0,46");
            this.dom_k.Items.Add("0,461");
            this.dom_k.Items.Add("0,462");
            this.dom_k.Items.Add("0,463");
            this.dom_k.Items.Add("0,464");
            this.dom_k.Items.Add("0,465");
            this.dom_k.Items.Add("0,466");
            this.dom_k.Items.Add("0,467");
            this.dom_k.Items.Add("0,468");
            this.dom_k.Items.Add("0,469");
            this.dom_k.Items.Add("0,47");
            this.dom_k.Items.Add("0,471");
            this.dom_k.Items.Add("0,472");
            this.dom_k.Items.Add("0,473");
            this.dom_k.Items.Add("0,474");
            this.dom_k.Items.Add("0,475");
            this.dom_k.Items.Add("0,476");
            this.dom_k.Items.Add("0,477");
            this.dom_k.Items.Add("0,478");
            this.dom_k.Items.Add("0,479");
            this.dom_k.Items.Add("0,48");
            this.dom_k.Items.Add("0,481");
            this.dom_k.Items.Add("0,482");
            this.dom_k.Items.Add("0,483");
            this.dom_k.Items.Add("0,484");
            this.dom_k.Items.Add("0,485");
            this.dom_k.Items.Add("0,486");
            this.dom_k.Items.Add("0,487");
            this.dom_k.Items.Add("0,488");
            this.dom_k.Items.Add("0,489");
            this.dom_k.Items.Add("0,49");
            this.dom_k.Items.Add("0,491");
            this.dom_k.Items.Add("0,492");
            this.dom_k.Items.Add("0,493");
            this.dom_k.Items.Add("0,494");
            this.dom_k.Items.Add("0,495");
            this.dom_k.Items.Add("0,496");
            this.dom_k.Items.Add("0,497");
            this.dom_k.Items.Add("0,498");
            this.dom_k.Items.Add("0,499");
            this.dom_k.Items.Add("0,5");
            this.dom_k.Items.Add("0,501");
            this.dom_k.Items.Add("0,502");
            this.dom_k.Items.Add("0,503");
            this.dom_k.Items.Add("0,504");
            this.dom_k.Items.Add("0,505");
            this.dom_k.Items.Add("0,506");
            this.dom_k.Items.Add("0,507");
            this.dom_k.Items.Add("0,508");
            this.dom_k.Items.Add("0,509");
            this.dom_k.Items.Add("0,51");
            this.dom_k.Items.Add("0,511");
            this.dom_k.Items.Add("0,512");
            this.dom_k.Items.Add("0,513");
            this.dom_k.Items.Add("0,514");
            this.dom_k.Items.Add("0,515");
            this.dom_k.Items.Add("0,516");
            this.dom_k.Items.Add("0,517");
            this.dom_k.Items.Add("0,518");
            this.dom_k.Items.Add("0,519");
            this.dom_k.Items.Add("0,52");
            this.dom_k.Items.Add("0,521");
            this.dom_k.Items.Add("0,522");
            this.dom_k.Items.Add("0,523");
            this.dom_k.Items.Add("0,524");
            this.dom_k.Items.Add("0,525");
            this.dom_k.Items.Add("0,526");
            this.dom_k.Items.Add("0,527");
            this.dom_k.Items.Add("0,528");
            this.dom_k.Items.Add("0,529");
            this.dom_k.Items.Add("0,53");
            this.dom_k.Items.Add("0,531");
            this.dom_k.Items.Add("0,532");
            this.dom_k.Items.Add("0,533");
            this.dom_k.Items.Add("0,534");
            this.dom_k.Items.Add("0,535");
            this.dom_k.Items.Add("0,536");
            this.dom_k.Items.Add("0,537");
            this.dom_k.Items.Add("0,538");
            this.dom_k.Items.Add("0,539");
            this.dom_k.Items.Add("0,54");
            this.dom_k.Items.Add("0,541");
            this.dom_k.Items.Add("0,542");
            this.dom_k.Items.Add("0,543");
            this.dom_k.Items.Add("0,544");
            this.dom_k.Items.Add("0,545");
            this.dom_k.Items.Add("0,546");
            this.dom_k.Items.Add("0,547");
            this.dom_k.Items.Add("0,548");
            this.dom_k.Items.Add("0,549");
            this.dom_k.Items.Add("0,55");
            this.dom_k.Items.Add("0,551");
            this.dom_k.Items.Add("0,552");
            this.dom_k.Items.Add("0,553");
            this.dom_k.Items.Add("0,554");
            this.dom_k.Items.Add("0,555");
            this.dom_k.Items.Add("0,556");
            this.dom_k.Items.Add("0,557");
            this.dom_k.Items.Add("0,558");
            this.dom_k.Items.Add("0,559");
            this.dom_k.Items.Add("0,56");
            this.dom_k.Items.Add("0,561");
            this.dom_k.Items.Add("0,562");
            this.dom_k.Items.Add("0,563");
            this.dom_k.Items.Add("0,564");
            this.dom_k.Items.Add("0,565");
            this.dom_k.Items.Add("0,566");
            this.dom_k.Items.Add("0,567");
            this.dom_k.Items.Add("0,568");
            this.dom_k.Items.Add("0,569");
            this.dom_k.Items.Add("0,57");
            this.dom_k.Items.Add("0,571");
            this.dom_k.Items.Add("0,572");
            this.dom_k.Items.Add("0,573");
            this.dom_k.Items.Add("0,574");
            this.dom_k.Items.Add("0,575");
            this.dom_k.Items.Add("0,576");
            this.dom_k.Items.Add("0,577");
            this.dom_k.Items.Add("0,578");
            this.dom_k.Items.Add("0,579");
            this.dom_k.Items.Add("0,58");
            this.dom_k.Items.Add("0,581");
            this.dom_k.Items.Add("0,582");
            this.dom_k.Items.Add("0,583");
            this.dom_k.Items.Add("0,584");
            this.dom_k.Items.Add("0,585");
            this.dom_k.Items.Add("0,586");
            this.dom_k.Items.Add("0,587");
            this.dom_k.Items.Add("0,588");
            this.dom_k.Items.Add("0,589");
            this.dom_k.Items.Add("0,59");
            this.dom_k.Items.Add("0,591");
            this.dom_k.Items.Add("0,592");
            this.dom_k.Items.Add("0,593");
            this.dom_k.Items.Add("0,594");
            this.dom_k.Items.Add("0,595");
            this.dom_k.Items.Add("0,596");
            this.dom_k.Items.Add("0,597");
            this.dom_k.Items.Add("0,598");
            this.dom_k.Items.Add("0,599");
            this.dom_k.Items.Add("0,6");
            this.dom_k.Items.Add("0,601");
            this.dom_k.Items.Add("0,602");
            this.dom_k.Items.Add("0,603");
            this.dom_k.Items.Add("0,604");
            this.dom_k.Items.Add("0,605");
            this.dom_k.Items.Add("0,606");
            this.dom_k.Items.Add("0,607");
            this.dom_k.Items.Add("0,608");
            this.dom_k.Items.Add("0,609");
            this.dom_k.Items.Add("0,61");
            this.dom_k.Items.Add("0,611");
            this.dom_k.Items.Add("0,612");
            this.dom_k.Items.Add("0,613");
            this.dom_k.Items.Add("0,614");
            this.dom_k.Items.Add("0,615");
            this.dom_k.Items.Add("0,616");
            this.dom_k.Items.Add("0,617");
            this.dom_k.Items.Add("0,618");
            this.dom_k.Items.Add("0,619");
            this.dom_k.Items.Add("0,62");
            this.dom_k.Items.Add("0,621");
            this.dom_k.Items.Add("0,622");
            this.dom_k.Items.Add("0,623");
            this.dom_k.Items.Add("0,624");
            this.dom_k.Items.Add("0,625");
            this.dom_k.Items.Add("0,626");
            this.dom_k.Items.Add("0,627");
            this.dom_k.Items.Add("0,628");
            this.dom_k.Items.Add("0,629");
            this.dom_k.Items.Add("0,63");
            this.dom_k.Items.Add("0,631");
            this.dom_k.Items.Add("0,632");
            this.dom_k.Items.Add("0,633");
            this.dom_k.Items.Add("0,634");
            this.dom_k.Items.Add("0,635");
            this.dom_k.Items.Add("0,636");
            this.dom_k.Items.Add("0,637");
            this.dom_k.Items.Add("0,638");
            this.dom_k.Items.Add("0,639");
            this.dom_k.Items.Add("0,64");
            this.dom_k.Items.Add("0,641");
            this.dom_k.Items.Add("0,642");
            this.dom_k.Items.Add("0,643");
            this.dom_k.Items.Add("0,644");
            this.dom_k.Items.Add("0,645");
            this.dom_k.Items.Add("0,646");
            this.dom_k.Items.Add("0,647");
            this.dom_k.Items.Add("0,648");
            this.dom_k.Items.Add("0,649");
            this.dom_k.Items.Add("0,65");
            this.dom_k.Items.Add("0,651");
            this.dom_k.Items.Add("0,652");
            this.dom_k.Items.Add("0,653");
            this.dom_k.Items.Add("0,654");
            this.dom_k.Items.Add("0,655");
            this.dom_k.Items.Add("0,656");
            this.dom_k.Items.Add("0,657");
            this.dom_k.Items.Add("0,658");
            this.dom_k.Items.Add("0,659");
            this.dom_k.Items.Add("0,66");
            this.dom_k.Items.Add("0,661");
            this.dom_k.Items.Add("0,662");
            this.dom_k.Items.Add("0,663");
            this.dom_k.Items.Add("0,664");
            this.dom_k.Items.Add("0,665");
            this.dom_k.Items.Add("0,666");
            this.dom_k.Items.Add("0,667");
            this.dom_k.Items.Add("0,668");
            this.dom_k.Items.Add("0,669");
            this.dom_k.Items.Add("0,67");
            this.dom_k.Items.Add("0,671");
            this.dom_k.Items.Add("0,672");
            this.dom_k.Items.Add("0,673");
            this.dom_k.Items.Add("0,674");
            this.dom_k.Items.Add("0,675");
            this.dom_k.Items.Add("0,676");
            this.dom_k.Items.Add("0,677");
            this.dom_k.Items.Add("0,678");
            this.dom_k.Items.Add("0,679");
            this.dom_k.Items.Add("0,68");
            this.dom_k.Items.Add("0,681");
            this.dom_k.Items.Add("0,682");
            this.dom_k.Items.Add("0,683");
            this.dom_k.Items.Add("0,684");
            this.dom_k.Items.Add("0,685");
            this.dom_k.Items.Add("0,686");
            this.dom_k.Items.Add("0,687");
            this.dom_k.Items.Add("0,688");
            this.dom_k.Items.Add("0,689");
            this.dom_k.Items.Add("0,69");
            this.dom_k.Items.Add("0,691");
            this.dom_k.Items.Add("0,692");
            this.dom_k.Items.Add("0,693");
            this.dom_k.Items.Add("0,694");
            this.dom_k.Items.Add("0,695");
            this.dom_k.Items.Add("0,696");
            this.dom_k.Items.Add("0,697");
            this.dom_k.Items.Add("0,698");
            this.dom_k.Items.Add("0,699");
            this.dom_k.Items.Add("0,7");
            this.dom_k.Items.Add("0,701");
            this.dom_k.Items.Add("0,702");
            this.dom_k.Items.Add("0,703");
            this.dom_k.Items.Add("0,704");
            this.dom_k.Items.Add("0,705");
            this.dom_k.Items.Add("0,706");
            this.dom_k.Items.Add("0,707");
            this.dom_k.Items.Add("0,708");
            this.dom_k.Items.Add("0,709");
            this.dom_k.Items.Add("0,71");
            this.dom_k.Items.Add("0,711");
            this.dom_k.Items.Add("0,712");
            this.dom_k.Items.Add("0,713");
            this.dom_k.Items.Add("0,714");
            this.dom_k.Items.Add("0,715");
            this.dom_k.Items.Add("0,716");
            this.dom_k.Items.Add("0,717");
            this.dom_k.Items.Add("0,718");
            this.dom_k.Items.Add("0,719");
            this.dom_k.Items.Add("0,72");
            this.dom_k.Items.Add("0,721");
            this.dom_k.Items.Add("0,722");
            this.dom_k.Items.Add("0,723");
            this.dom_k.Items.Add("0,724");
            this.dom_k.Items.Add("0,725");
            this.dom_k.Items.Add("0,726");
            this.dom_k.Items.Add("0,727");
            this.dom_k.Items.Add("0,728");
            this.dom_k.Items.Add("0,729");
            this.dom_k.Items.Add("0,73");
            this.dom_k.Items.Add("0,731");
            this.dom_k.Items.Add("0,732");
            this.dom_k.Items.Add("0,733");
            this.dom_k.Items.Add("0,734");
            this.dom_k.Items.Add("0,735");
            this.dom_k.Items.Add("0,736");
            this.dom_k.Items.Add("0,737");
            this.dom_k.Items.Add("0,738");
            this.dom_k.Items.Add("0,739");
            this.dom_k.Items.Add("0,74");
            this.dom_k.Items.Add("0,741");
            this.dom_k.Items.Add("0,742");
            this.dom_k.Items.Add("0,743");
            this.dom_k.Items.Add("0,744");
            this.dom_k.Items.Add("0,745");
            this.dom_k.Items.Add("0,746");
            this.dom_k.Items.Add("0,747");
            this.dom_k.Items.Add("0,748");
            this.dom_k.Items.Add("0,749");
            this.dom_k.Items.Add("0,75");
            this.dom_k.Items.Add("0,751");
            this.dom_k.Items.Add("0,752");
            this.dom_k.Items.Add("0,753");
            this.dom_k.Items.Add("0,754");
            this.dom_k.Items.Add("0,755");
            this.dom_k.Items.Add("0,756");
            this.dom_k.Items.Add("0,757");
            this.dom_k.Items.Add("0,758");
            this.dom_k.Items.Add("0,759");
            this.dom_k.Items.Add("0,76");
            this.dom_k.Items.Add("0,761");
            this.dom_k.Items.Add("0,762");
            this.dom_k.Items.Add("0,763");
            this.dom_k.Items.Add("0,764");
            this.dom_k.Items.Add("0,765");
            this.dom_k.Items.Add("0,766");
            this.dom_k.Items.Add("0,767");
            this.dom_k.Items.Add("0,768");
            this.dom_k.Items.Add("0,769");
            this.dom_k.Items.Add("0,77");
            this.dom_k.Items.Add("0,771");
            this.dom_k.Items.Add("0,772");
            this.dom_k.Items.Add("0,773");
            this.dom_k.Items.Add("0,774");
            this.dom_k.Items.Add("0,775");
            this.dom_k.Items.Add("0,776");
            this.dom_k.Items.Add("0,777");
            this.dom_k.Items.Add("0,778");
            this.dom_k.Items.Add("0,779");
            this.dom_k.Items.Add("0,78");
            this.dom_k.Items.Add("0,781");
            this.dom_k.Items.Add("0,782");
            this.dom_k.Items.Add("0,783");
            this.dom_k.Items.Add("0,784");
            this.dom_k.Items.Add("0,785");
            this.dom_k.Items.Add("0,786");
            this.dom_k.Items.Add("0,787");
            this.dom_k.Items.Add("0,788");
            this.dom_k.Items.Add("0,789");
            this.dom_k.Items.Add("0,79");
            this.dom_k.Items.Add("0,791");
            this.dom_k.Items.Add("0,792");
            this.dom_k.Items.Add("0,793");
            this.dom_k.Items.Add("0,794");
            this.dom_k.Items.Add("0,795");
            this.dom_k.Items.Add("0,796");
            this.dom_k.Items.Add("0,797");
            this.dom_k.Items.Add("0,798");
            this.dom_k.Items.Add("0,799");
            this.dom_k.Items.Add("0,8");
            this.dom_k.Items.Add("0,801");
            this.dom_k.Items.Add("0,802");
            this.dom_k.Items.Add("0,803");
            this.dom_k.Items.Add("0,804");
            this.dom_k.Items.Add("0,805");
            this.dom_k.Items.Add("0,806");
            this.dom_k.Items.Add("0,807");
            this.dom_k.Items.Add("0,808");
            this.dom_k.Items.Add("0,809");
            this.dom_k.Items.Add("0,81");
            this.dom_k.Items.Add("0,811");
            this.dom_k.Items.Add("0,812");
            this.dom_k.Items.Add("0,813");
            this.dom_k.Items.Add("0,814");
            this.dom_k.Items.Add("0,815");
            this.dom_k.Items.Add("0,816");
            this.dom_k.Items.Add("0,817");
            this.dom_k.Items.Add("0,818");
            this.dom_k.Items.Add("0,819");
            this.dom_k.Items.Add("0,82");
            this.dom_k.Items.Add("0,821");
            this.dom_k.Items.Add("0,822");
            this.dom_k.Items.Add("0,823");
            this.dom_k.Items.Add("0,824");
            this.dom_k.Items.Add("0,825");
            this.dom_k.Items.Add("0,826");
            this.dom_k.Items.Add("0,827");
            this.dom_k.Items.Add("0,828");
            this.dom_k.Items.Add("0,829");
            this.dom_k.Items.Add("0,83");
            this.dom_k.Items.Add("0,831");
            this.dom_k.Items.Add("0,832");
            this.dom_k.Items.Add("0,833");
            this.dom_k.Items.Add("0,834");
            this.dom_k.Items.Add("0,835");
            this.dom_k.Items.Add("0,836");
            this.dom_k.Items.Add("0,837");
            this.dom_k.Items.Add("0,838");
            this.dom_k.Items.Add("0,839");
            this.dom_k.Items.Add("0,84");
            this.dom_k.Items.Add("0,841");
            this.dom_k.Items.Add("0,842");
            this.dom_k.Items.Add("0,843");
            this.dom_k.Items.Add("0,844");
            this.dom_k.Items.Add("0,845");
            this.dom_k.Items.Add("0,846");
            this.dom_k.Items.Add("0,847");
            this.dom_k.Items.Add("0,848");
            this.dom_k.Items.Add("0,849");
            this.dom_k.Items.Add("0,85");
            this.dom_k.Items.Add("0,851");
            this.dom_k.Items.Add("0,852");
            this.dom_k.Items.Add("0,853");
            this.dom_k.Items.Add("0,854");
            this.dom_k.Items.Add("0,855");
            this.dom_k.Items.Add("0,856");
            this.dom_k.Items.Add("0,857");
            this.dom_k.Items.Add("0,858");
            this.dom_k.Items.Add("0,859");
            this.dom_k.Items.Add("0,86");
            this.dom_k.Items.Add("0,861");
            this.dom_k.Items.Add("0,862");
            this.dom_k.Items.Add("0,863");
            this.dom_k.Items.Add("0,864");
            this.dom_k.Items.Add("0,865");
            this.dom_k.Items.Add("0,866");
            this.dom_k.Items.Add("0,867");
            this.dom_k.Items.Add("0,868");
            this.dom_k.Items.Add("0,869");
            this.dom_k.Items.Add("0,87");
            this.dom_k.Items.Add("0,871");
            this.dom_k.Items.Add("0,872");
            this.dom_k.Items.Add("0,873");
            this.dom_k.Items.Add("0,874");
            this.dom_k.Items.Add("0,875");
            this.dom_k.Items.Add("0,876");
            this.dom_k.Items.Add("0,877");
            this.dom_k.Items.Add("0,878");
            this.dom_k.Items.Add("0,879");
            this.dom_k.Items.Add("0,88");
            this.dom_k.Items.Add("0,881");
            this.dom_k.Items.Add("0,882");
            this.dom_k.Items.Add("0,883");
            this.dom_k.Items.Add("0,884");
            this.dom_k.Items.Add("0,885");
            this.dom_k.Items.Add("0,886");
            this.dom_k.Items.Add("0,887");
            this.dom_k.Items.Add("0,888");
            this.dom_k.Items.Add("0,889");
            this.dom_k.Items.Add("0,89");
            this.dom_k.Items.Add("0,891");
            this.dom_k.Items.Add("0,892");
            this.dom_k.Items.Add("0,893");
            this.dom_k.Items.Add("0,894");
            this.dom_k.Items.Add("0,895");
            this.dom_k.Items.Add("0,896");
            this.dom_k.Items.Add("0,897");
            this.dom_k.Items.Add("0,898");
            this.dom_k.Items.Add("0,899");
            this.dom_k.Items.Add("0,9");
            this.dom_k.Items.Add("0,901");
            this.dom_k.Items.Add("0,902");
            this.dom_k.Items.Add("0,903");
            this.dom_k.Items.Add("0,904");
            this.dom_k.Items.Add("0,905");
            this.dom_k.Items.Add("0,906");
            this.dom_k.Items.Add("0,907");
            this.dom_k.Items.Add("0,908");
            this.dom_k.Items.Add("0,909");
            this.dom_k.Items.Add("0,91");
            this.dom_k.Items.Add("0,911");
            this.dom_k.Items.Add("0,912");
            this.dom_k.Items.Add("0,913");
            this.dom_k.Items.Add("0,914");
            this.dom_k.Items.Add("0,915");
            this.dom_k.Items.Add("0,916");
            this.dom_k.Items.Add("0,917");
            this.dom_k.Items.Add("0,918");
            this.dom_k.Items.Add("0,919");
            this.dom_k.Items.Add("0,92");
            this.dom_k.Items.Add("0,921");
            this.dom_k.Items.Add("0,922");
            this.dom_k.Items.Add("0,923");
            this.dom_k.Items.Add("0,924");
            this.dom_k.Items.Add("0,925");
            this.dom_k.Items.Add("0,926");
            this.dom_k.Items.Add("0,927");
            this.dom_k.Items.Add("0,928");
            this.dom_k.Items.Add("0,929");
            this.dom_k.Items.Add("0,93");
            this.dom_k.Items.Add("0,931");
            this.dom_k.Items.Add("0,932");
            this.dom_k.Items.Add("0,933");
            this.dom_k.Items.Add("0,934");
            this.dom_k.Items.Add("0,935");
            this.dom_k.Items.Add("0,936");
            this.dom_k.Items.Add("0,937");
            this.dom_k.Items.Add("0,938");
            this.dom_k.Items.Add("0,939");
            this.dom_k.Items.Add("0,94");
            this.dom_k.Items.Add("0,941");
            this.dom_k.Items.Add("0,942");
            this.dom_k.Items.Add("0,943");
            this.dom_k.Items.Add("0,944");
            this.dom_k.Items.Add("0,945");
            this.dom_k.Items.Add("0,946");
            this.dom_k.Items.Add("0,947");
            this.dom_k.Items.Add("0,948");
            this.dom_k.Items.Add("0,949");
            this.dom_k.Items.Add("0,95");
            this.dom_k.Location = new System.Drawing.Point(63, 241);
            this.dom_k.Name = "dom_k";
            this.dom_k.Size = new System.Drawing.Size(92, 25);
            this.dom_k.TabIndex = 17;
            this.dom_k.Text = "choice_k";
            // 
            // nudResol
            // 
            this.nudResol.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.nudResol.Font = new System.Drawing.Font("Times New Roman", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.nudResol.Hexadecimal = true;
            this.nudResol.Location = new System.Drawing.Point(44, 149);
            this.nudResol.Maximum = new decimal(new int[] {
            8,
            0,
            0,
            0});
            this.nudResol.Minimum = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.nudResol.Name = "nudResol";
            this.nudResol.Size = new System.Drawing.Size(54, 27);
            this.nudResol.TabIndex = 18;
            this.nudResol.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.nudResol.Value = new decimal(new int[] {
            2,
            0,
            0,
            0});
            // 
            // nudResolution
            // 
            this.nudResolution.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.nudResolution.AutoSize = true;
            this.nudResolution.Font = new System.Drawing.Font("Times New Roman", 10.2F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.nudResolution.Location = new System.Drawing.Point(115, 151);
            this.nudResolution.Name = "nudResolution";
            this.nudResolution.Size = new System.Drawing.Size(85, 19);
            this.nudResolution.TabIndex = 19;
            this.nudResolution.Text = "Resolution";
            // 
            // Dissolution_model
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1085, 710);
            this.Controls.Add(this.nudResolution);
            this.Controls.Add(this.nudResol);
            this.Controls.Add(this.dom_k);
            this.Controls.Add(this.dom_Dt);
            this.Controls.Add(this.butStop);
            this.Controls.Add(this.pictGraphic);
            this.Controls.Add(this.pictProcess);
            this.Controls.Add(this.butClose);
            this.Controls.Add(this.butStart);
            this.Controls.Add(this.nudConc);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.splitter1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Dissolution_model";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Dissolution model";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            ((System.ComponentModel.ISupportInitialize)(this.nudConc)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictProcess)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictGraphic)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudResol)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Splitter splitter1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.NumericUpDown nudConc;
        private System.Windows.Forms.Button butStart;
        private System.Windows.Forms.Button butClose;
        private System.Windows.Forms.PictureBox pictProcess;
        private System.Windows.Forms.PictureBox pictGraphic;
        private System.Windows.Forms.Button butStop;
        private System.Windows.Forms.Timer timerDisplay;
        private System.Windows.Forms.DomainUpDown dom_Dt;
        private System.Windows.Forms.DomainUpDown dom_k;
        private System.Windows.Forms.NumericUpDown nudResol;
        private System.Windows.Forms.Label nudResolution;
    }
}

